# Disabled cache in hope of improving reliability of AppVeyor builds
cache:
- "c:\\sr" # stack root, short paths == fewer problems
- "C:\stack\.stack-work"

build: off

before_test:
- curl -sS -ostack.zip -L --insecure http://www.stackage.org/stack/windows-i386
- 7z x stack.zip stack.exe

clone_folder: "c:\\stack"
environment:
  global:
    STACK_ROOT: "c:\\sr"
  matrix: 
    - lts: --resolver lts-3
    # - lts: --resolver lts-6
    # - lts: --resolver lts-7
    - lts: ""

platform:
  # - x86
  - x64

test_script:
- stack setup > nul
# The ugly echo "" hack is to avoid complaints about 0 being an invalid file
# descriptor
# - cmd: echo $lts$ $(lts) {lts} $lts
- cmd: echo %lts% # $(lts) {lts} $lts
- cmd: echo "" | stack --no-terminal test %lts%
